const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STATE_KEY='housemade-v2-state';
const CHANNEL_LABELS={copy:'Copy message',sms:'Text message',email:'Email',alexa:'Alexa / voice prompt'};
const ICONS={
 bath:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path d="M4 11h16v2a6 6 0 0 1-6 6h-4a6 6 0 0 1-6-6v-2Z"/><path d="M6 11V6a3 3 0 0 1 3-3h1"/><path d="M4 21l2-3M20 21l-2-3"/></svg>',
 kitchen:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path d="M4 9h16l-2 10H6L4 9Z"/><path d="M8 9a4 4 0 0 1 8 0M3 9h18M9 4h6"/></svg>',
 washer:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><rect x="5" y="2.5" width="14" height="19" rx="2"/><circle cx="12" cy="13" r="4.5"/><path d="M8 6h.01M11 6h4"/></svg>',
 bed:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path d="M3 19v-8h18v8M3 16h18M6 11V7h5a3 3 0 0 1 3 3v1M3 21v-2M21 21v-2"/></svg>',
 sofa:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path d="M5 12V8a3 3 0 0 1 3-3h8a3 3 0 0 1 3 3v4"/><path d="M4 11a2 2 0 0 0-2 2v5h20v-5a2 2 0 0 0-2-2 2 2 0 0 0-2 2v1H6v-1a2 2 0 0 0-2-2Z"/><path d="M5 18v2M19 18v2"/></svg>',
 garage:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path d="M3 10l9-7 9 7v11H3V10Z"/><path d="M7 21V11h10v10M7 14h10M7 17h10"/></svg>',
 dishes:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><path d="M3 21h18"/></svg>',
 door:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path d="M5 21V3h12v18M9 21V7h8v14"/><circle cx="14" cy="14" r=".6" fill="currentColor"/></svg>',
 sparkle:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 2l1.5 5.5L19 9l-5.5 1.5L12 16l-1.5-5.5L5 9l5.5-1.5L12 2Z"/><path d="M18 14l.8 3 3.2.8-3.2.8-.8 3-.8-3-3.2-.8 3.2-.8.8-3Z"/></svg>'
};
const ICON_KEYS=Object.keys(ICONS);
const DEFAULT_PRESETS=['Sink','Toilet','Trash','Shower','Bathtub','Mirror','Windows','Mop floor','Vacuum','Sweep floor','Shelves','Toothbrush holder','Faucets','Baseboards','Towels','Cabinet fronts','Light switches','Door handles','Vent','Grout','Drain','Dishes','Counters','Stovetop','Oven','Microwave','Fridge shelves','Backsplash','Dishwasher','Coffee area','Pantry','Make bed','Change sheets','Clothes away','Nightstands','Under bed','Dust surfaces','Cushions','Tables','Electronics','Vacuum sofa','Start load','Dry load','Fold','Put away','Clean washer seal','Lint trap','Wipe machines','Sort products','Put tools away','Workbench','Sort storage','Floor edges','Dish rack','Clean sink','Pet area','Toy pickup','Stairs','Entryway','Porch'];
const DEFAULT_LIBRARY=[
 {id:'bathroom',name:'Bathroom',icon:'bath',color:'#8EC9DF',quick:['Sink','Toilet','Trash','Shower'],deep:['Sink','Toilet','Trash','Shower','Mirror','Windows','Mop floor','Shelves','Toothbrush holder','Faucets','Baseboards','Grout']},
 {id:'kitchen',name:'Kitchen',icon:'kitchen',color:'#F1B394',quick:['Dishes','Counters','Sink','Trash','Sweep floor'],deep:['Dishes','Counters','Sink','Trash','Sweep floor','Mop floor','Stovetop','Oven','Microwave','Fridge shelves','Cabinet fronts','Backsplash']},
 {id:'laundry',name:'Laundry',icon:'washer',color:'#9FD6C1',quick:['Start load','Dry load','Fold','Put away'],deep:['Start load','Dry load','Fold','Put away','Clean washer seal','Lint trap','Wipe machines','Sort products','Sweep floor','Mop floor']},
 {id:'bedroom',name:'Bedroom',icon:'bed',color:'#D7A7C3',quick:['Make bed','Clothes away','Trash','Dust surfaces','Vacuum'],deep:['Make bed','Change sheets','Clothes away','Trash','Dust surfaces','Nightstands','Mirror','Windows','Vacuum','Under bed','Baseboards']},
 {id:'living',name:'Living Room',icon:'sofa',color:'#C6B0E8',quick:['Toy pickup','Cushions','Dust surfaces','Vacuum'],deep:['Toy pickup','Cushions','Dust surfaces','Tables','Electronics','Windows','Shelves','Vacuum sofa','Vacuum','Baseboards']},
 {id:'garage',name:'Garage',icon:'garage',color:'#A9BBCD',quick:['Trash','Put tools away','Sweep floor'],deep:['Trash','Put tools away','Sweep floor','Shelves','Workbench','Sort storage','Windows','Floor edges']},
 {id:'dishes',name:'Dishes',icon:'dishes',color:'#E6C16F',quick:['Load dishwasher','Wash dishes','Dry','Put away'],deep:['Load dishwasher','Wash dishes','Dry','Put away','Clean sink','Dish rack','Drain','Cabinet fronts']}
];
const QUOTES=[
 'Time to toi-let the bathroom know who’s boss.','Tiny reset. Big main-character energy.','Future-you just sent a thank-you note.','Dust has had a good run. End the era.','A ten-minute tidy still counts as domestic wizardry.','No cape required. Just start with one little thing.','Plot twist: the laundry mountain is climbable.','You bring the playlist. We’ll bring the momentum.','This room is about to receive an unsolicited glow-up.','Clean now, smug later.','One sparkle at a time. Very scientific.','The floor called. It would like its personality back.','We are not deep-cleaning the universe. Just this room.','Domestic chaos, meet your extremely organized opponent.','If it takes less than two songs, it barely counts as work.','Let’s turn “I should” into “already did.”','Today’s forecast: scattered mess with a strong chance of sorted.','The sink has been getting a little too confident.','Cue the montage. Preferably with excellent music.','One room. One reset. Zero need for perfection.','The dust bunnies have received their eviction notice.','A quick clean is still a clean. We checked.','Deep Clean mode: because apparently we enjoy visible evidence of progress.','Go on. Give the mirror something clean to reflect.','Tiny task. Ridiculous satisfaction.','Good enough and finished beats perfect and avoided.','Start with the easiest circle. Momentum is wonderfully gullible.','Let the mop have its moment.','Countertops: prepare to re-enter society.','The house is not judging you. HouseMade is lightly cheering.','The laundry chair has enjoyed retirement for long enough.','Put it away now and deny tomorrow-you the complaint.','A five-minute reset can be suspiciously effective.','Nothing dramatic. Just a small domestic victory.','Quick Clean: maximum visible improvement per minute.','Deep Clean: we’re going behind things now. Brave.','The vacuum is ready for its world tour.','If the playlist is good enough, this technically counts as dancing.','Housework, but with better branding and tiny gold coins.','The goal is calmer, not perfect.','A completed circle is a tiny receipt proving you did the thing.','Your future self has already begun acting smug.','No speeches. One task. Go.','Dishes first. Existential questions later.','The garage is about to remember it has a floor.','Laundry: the sequel nobody asked for, now with folding.','Clean surfaces, clearer brain. Convenient coincidence.','Make the bed and suddenly the whole room starts behaving.','We believe in you. More importantly, we believe in timers.','Do the small obvious thing first. It’s practically cheating.','One tap closer to gold.','Less “I really should.” More “already did.”'
];
const REMINDER_TEMPLATES=[
 (n,t)=>`${n}, don’t forget — it’s your turn for ${t}. Future-you will be glad you did.`,
 (n,t)=>`Hey ${n}! HouseMade check-in: ${t} is waiting. One quick reset and you’re done.`,
 (n,t)=>`${n}, domestic fame awaits. ${t} is up. Playlist on, job done.`,
 (n,t)=>`Friendly nudge for ${n}: ${t} today. A cleaner room and unreasonable levels of satisfaction await.`,
 (n,t)=>`${n}, ${t} has formally requested your presence. No meeting invite required.`,
 (n,t)=>`HouseMade dispatch for ${n}: ${t}. Tiny mission. Big smug-afterwards energy.`
];
const defaultState={version:2,profile:null,householdName:'Our House',members:[],library:structuredClone(DEFAULT_LIBRARY),presetItems:[...DEFAULT_PRESETS],schedule:[
 {id:'s1',taskId:'bathroom',day:1,repeat:'weekly',mode:'quick',memberId:null,time:'18:00',startDate:new Date().toISOString()},
 {id:'s2',taskId:'dishes',day:2,repeat:'weekly',mode:'quick',memberId:null,time:'19:00',startDate:new Date().toISOString()},
 {id:'s3',taskId:'laundry',day:3,repeat:'weekly',mode:'quick',memberId:null,time:'17:30',startDate:new Date().toISOString()},
 {id:'s4',taskId:'kitchen',day:5,repeat:'weekly',mode:'deep',memberId:null,time:'18:00',startDate:new Date().toISOString()}],completions:{},settings:{musicUrl:'',sound:true,night:false,defaultTimer:15,notifications:false},notificationHistory:{},view:'week',monthOffset:0};
let state=loadState(), currentTask=null,currentMode='quick',currentMember=null,timer={running:false,remaining:0,total:0,id:null,selected:15};
let deferredInstallPrompt=null;
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STATE_KEY)||'{}');return deepMerge(structuredClone(defaultState),saved)}catch{return structuredClone(defaultState)}}
function deepMerge(base,extra){if(!extra||typeof extra!=='object')return base;for(const[k,v]of Object.entries(extra)){if(v&&typeof v==='object'&&!Array.isArray(v)&&base[k]&&typeof base[k]==='object'&&!Array.isArray(base[k]))base[k]=deepMerge(base[k],v);else base[k]=v}return base}
function save(){localStorage.setItem(STATE_KEY,JSON.stringify(state))}
function uid(p='id'){return p+Math.random().toString(36).slice(2,9)}
function iconMarkup(k){return ICONS[k]||ICONS.sparkle}
function getTask(id){return state.library.find(t=>t.id===id)}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast._id);toast._id=setTimeout(()=>el.classList.remove('show'),2200)}
function isStandalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function startOfWeek(d){const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-x.getDay());return x}
function firstDueDate(item){const base=new Date(item.startDate||Date.now());base.setHours(0,0,0,0);while(base.getDay()!==Number(item.day))base.setDate(base.getDate()+1);return base}
function occursOn(item,date){const d=new Date(date);d.setHours(0,0,0,0);if(d.getDay()!==Number(item.day))return false;const first=firstDueDate(item);if(d<first)return false;const days=Math.round((d-first)/86400000);if(item.repeat==='biweekly')return days%14===0;if(item.repeat==='monthly')return Math.ceil(d.getDate()/7)===Math.ceil(first.getDate()/7);return days%7===0}
function completionKey(item,date,mode=item.mode){return `${item.id}:${dateKey(date)}:${mode}`}
function completionFor(item,date,mode=item.mode){return state.completions[completionKey(item,date,mode)]||{done:[],all:false}}
function isComplete(item,date,mode=item.mode){return !!completionFor(item,date,mode).all}
function setNight(){document.body.classList.toggle('night',!!state.settings.night);$('#themeToggle')?.setAttribute('aria-pressed',String(!!state.settings.night))}
async function hashPin(pin){const data=new TextEncoder().encode(pin);const hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}

function setupGate(){if(isStandalone()){showApp()}else{showGate()}}
function showGate(){ $('#browserGate').classList.remove('hidden');$('#app').classList.add('hidden');const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);$('#installSteps').innerHTML=ios?'<b>Install HouseMade</b>Tap <strong>Share</strong> → <strong>Add to Home Screen</strong> → <strong>Add</strong>.':'<b>Install HouseMade</b>Use your browser menu and choose <strong>Install app</strong> or <strong>Add to Home Screen</strong>.'; }
function showApp(){ $('#browserGate').classList.add('hidden');$('#app').classList.remove('hidden');setNight();renderAll(); if(!state.profile){$('#onboarding').classList.remove('hidden');return}if(state.profile.pinHash&&sessionStorage.getItem('hm-unlocked')!=='1'){showLock();return}startGreeting();startReminderChecker() }
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installBtn').classList.remove('hidden')});
$('#installBtn').onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installBtn').classList.add('hidden')};

function startGreeting(){if(!state.profile)return;$('#greetingHey').textContent=`Hey ${state.profile.firstName},`;$('#greetingMake').textContent='let’s get this house made…';$('#greetingTogether').textContent='together!';const card=$('#greetingCard');card.classList.remove('play');void card.offsetWidth;card.classList.add('play');createParticles($('#greetingParticles'),28);if(state.settings.sound)chime('shimmer')}
function createParticles(container,count){container.innerHTML='';for(let i=0;i<count;i++){const p=document.createElement('i');p.style.left=`${-15+Math.random()*35}%`;p.style.top=`${20+Math.random()*70}%`;p.style.animationDelay=`${Math.random()*.8}s`;p.style.animationDuration=`${2+Math.random()*1.4}s`;container.appendChild(p)}}
function showLock(){ $('#lockName').textContent=state.profile.firstName;$('#lockScreen').classList.remove('hidden');$('#unlockPin').value='';$('#unlockError').textContent='';setTimeout(()=>$('#unlockPin').focus(),180)}

function renderAll(){renderSelectors();renderPlanner();renderUpNext();renderScheduleList();renderMembers();renderTasks();renderPresetLibrary();renderSettings();updateNotificationDot()}
function renderSelectors(){fillSelect($('#schedTask'),state.library.map(t=>[t.id,t.name]));fillSelect($('#schedMember'),[['','Anyone'],...state.members.map(m=>[m.id,m.name])]);$$('.segment').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view))}
function fillSelect(select,items){const prev=select.value;select.innerHTML='';items.forEach(([v,l])=>{const o=document.createElement('option');o.value=v;o.textContent=l;select.appendChild(o)});if([...select.options].some(o=>o.value===prev))select.value=prev}
function plannerDates(){const now=new Date();now.setHours(0,0,0,0);if(state.view==='day')return[now];if(state.view==='week'){const s=startOfWeek(now);return Array.from({length:7},(_,i)=>{const d=new Date(s);d.setDate(s.getDate()+i);return d})}const first=new Date(now.getFullYear(),now.getMonth()+state.monthOffset,1);const grid=startOfWeek(first);return Array.from({length:42},(_,i)=>{const d=new Date(grid);d.setDate(grid.getDate()+i);return d})}
function renderPlanner(){const dates=plannerDates(),wrap=$('#planner');wrap.innerHTML='';wrap.className='planner'+(state.view==='month'?' month':'');const currentMonth=new Date().getMonth()+state.monthOffset;dates.forEach((d,index)=>{const day=document.createElement('article');day.className='planner-day'+(dateKey(d)===dateKey(new Date())?' today':'');if(state.view==='month'&&d.getMonth()!==((currentMonth%12)+12)%12)day.style.opacity='.42';const title=document.createElement('div');title.className='day-title';title.innerHTML=`<b>${d.toLocaleDateString(undefined,{weekday:'short'})}</b><span>${d.getDate()}</span>`;day.appendChild(title);state.schedule.filter(s=>occursOn(s,d)).forEach((item,j)=>day.appendChild(choreChip(item,d,index*2+j)));wrap.appendChild(day)});const total=dates.reduce((n,d)=>n+state.schedule.filter(s=>occursOn(s,d)).length,0);$('#plannerSummary').textContent=`${total} scheduled`;const pc=$('#periodControls');if(state.view==='month'){pc.classList.remove('hidden');const monthDate=new Date(new Date().getFullYear(),new Date().getMonth()+state.monthOffset,1);$('#periodLabel').textContent=monthDate.toLocaleDateString(undefined,{month:'long',year:'numeric'})}else pc.classList.add('hidden')}
function choreChip(item,date,delay=0){const t=getTask(item.taskId),member=state.members.find(m=>m.id===item.memberId);const b=document.createElement('button');b.className='chore-chip'+(isComplete(item,date)?' completed':'');b.style.setProperty('--task',t?.color||'#B59EE2');b.style.animationDelay=`${Math.min(delay*.025,.35)}s`;b.innerHTML=`<span class="chip-icon">${isComplete(item,date)?'✓':iconMarkup(t?.icon)}</span><span class="chip-copy"><b></b><small></small></span>`;b.querySelector('b').textContent=t?.name||'Task';b.querySelector('small').textContent=`${item.mode==='deep'?'Deep Clean':'Quick Clean'}${member?' · '+member.name:''}`;b.onclick=()=>openTask(item,date);return b}
function nextOccurrences(limit=5){const out=[],start=new Date();start.setHours(0,0,0,0);for(let i=0;i<35&&out.length<limit;i++){const d=new Date(start);d.setDate(start.getDate()+i);state.schedule.filter(s=>occursOn(s,d)).forEach(s=>out.push({item:s,date:d}));}return out.slice(0,limit)}
function renderUpNext(){const wrap=$('#upNext');wrap.innerHTML='';nextOccurrences(3).forEach(({item,date})=>{const t=getTask(item.taskId),member=state.members.find(m=>m.id===item.memberId);const b=document.createElement('button');b.className='up-card';b.style.setProperty('--task',t.color);b.innerHTML=`<span class="up-icon">${iconMarkup(t.icon)}</span><div><b></b><small></small></div><span>›</span>`;b.querySelector('b').textContent=t.name;b.querySelector('small').textContent=`${date.toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short'})} · ${item.mode==='deep'?'Deep':'Quick'}${member?' · '+member.name:''}`;b.onclick=()=>openTask(item,date);wrap.appendChild(b)})}
function renderScheduleList(){const wrap=$('#scheduleList');wrap.innerHTML='';if(!state.schedule.length){wrap.innerHTML='<div class="surface muted">No chores scheduled yet.</div>';return}state.schedule.forEach(item=>{const t=getTask(item.taskId),m=state.members.find(x=>x.id===item.memberId);const row=document.createElement('div');row.className='list-row';row.innerHTML=`<div class="list-symbol" style="background:${t?.color||'#B59EE2'}">${iconMarkup(t?.icon)}</div><div class="list-copy"><b></b><span></span></div><div class="list-actions"><button class="tiny-btn danger-btn">Remove</button></div>`;row.querySelector('.list-copy b').textContent=`${t?.name||'Task'} · ${item.mode==='deep'?'Deep':'Quick'}`;row.querySelector('.list-copy span').textContent=`${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][item.day]} · ${item.repeat} · ${item.time||'18:00'}${m?' · '+m.name:''}`;row.querySelector('button').onclick=()=>{state.schedule=state.schedule.filter(x=>x.id!==item.id);save();renderAll();toast('Schedule item removed')};wrap.appendChild(row)})}
function renderMembers(){const wrap=$('#memberList');wrap.innerHTML='';if(!state.members.length){wrap.innerHTML='<div class="surface muted">Add family members to assign chores and generate friendly prompts.</div>';return}state.members.forEach(m=>{const row=document.createElement('div');row.className='list-row';row.innerHTML=`<div class="avatar">${(m.name[0]||'?').toUpperCase()}</div><div class="list-copy"><b></b><span></span></div><div class="list-actions"><button class="tiny-btn prompt">Prompt</button><button class="tiny-btn danger-btn remove">Remove</button></div>`;row.querySelector('b').textContent=m.name;row.querySelector('span').textContent=`${CHANNEL_LABELS[m.channel]||m.channel}${m.contact?' · '+m.contact:''}`;row.querySelector('.prompt').onclick=()=>openReminder(m);row.querySelector('.remove').onclick=()=>{state.members=state.members.filter(x=>x.id!==m.id);state.schedule=state.schedule.map(s=>s.memberId===m.id?{...s,memberId:null}:s);save();renderAll();toast(`${m.name} removed`)};wrap.appendChild(row)})}
function renderTasks(){const wrap=$('#taskLibrary');wrap.innerHTML='';state.library.forEach(t=>{const b=document.createElement('button');b.className='task-card';b.style.setProperty('--task',t.color);b.innerHTML=`<span class="task-card-icon">${iconMarkup(t.icon)}</span><div><b></b><small></small></div><span>›</span>`;b.querySelector('b').textContent=t.name;b.querySelector('small').textContent=`${t.quick.length} quick · ${t.deep.length} deep`;b.onclick=()=>editTask(t.id);wrap.appendChild(b)})}
function renderPresetLibrary(){const wrap=$('#presetLibrary');wrap.innerHTML='';state.presetItems.forEach(item=>{const chip=document.createElement('span');chip.className='preset-pill';const label=document.createElement('span');label.textContent=item;const del=document.createElement('button');del.textContent='×';del.setAttribute('aria-label',`Remove ${item}`);del.onclick=()=>{state.presetItems=state.presetItems.filter(x=>x!==item);save();renderPresetLibrary();toast('Preset removed')};chip.append(label,del);wrap.appendChild(chip)})}
function renderSettings(){if(!state.profile)return;$('#settingsName').value=state.profile.firstName||'';$('#settingsHouse').value=state.householdName||'Our House';$('#musicUrl').value=state.settings.musicUrl||'';$('#defaultTimer').value=state.settings.defaultTimer||15;$('#soundToggle').setAttribute('aria-pressed',String(!!state.settings.sound));$('#themeToggle').setAttribute('aria-pressed',String(!!state.settings.night));setNight()}
function updateNotificationDot(){const upcoming=nextOccurrences(4).some(({item,date})=>!isComplete(item,date));$('#notificationDot').classList.toggle('hidden',!upcoming)}

function go(panel){const id=`${panel}Panel`;$$('.panel').forEach(p=>p.classList.toggle('active-panel',p.id===id));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.go===panel));scrollTo({top:0,behavior:'smooth'});if(panel==='home')startGreeting()}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('.segment').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.monthOffset=0;save();renderPlanner();$$('.segment').forEach(x=>x.classList.toggle('active',x===b))});$('#prevPeriod').onclick=()=>{state.monthOffset--;save();renderPlanner()};$('#nextPeriod').onclick=()=>{state.monthOffset++;save();renderPlanner()};

$('#onboardBtn').onclick=async()=>{const name=$('#firstName').value.trim();if(!name){toast('Add your first name');return}const pin=$('#pin').value.trim();if(pin&&!/^\d{4,8}$/.test(pin)){toast('PIN should be 4–8 digits');return}state.profile={firstName:name,pinHash:pin?await hashPin(pin):null};state.householdName=$('#houseName').value.trim()||'Our House';save();sessionStorage.setItem('hm-unlocked','1');$('#onboarding').classList.add('hidden');renderAll();startGreeting()};
$('#unlockBtn').onclick=async()=>{const v=$('#unlockPin').value.trim();if(await hashPin(v)===state.profile.pinHash){sessionStorage.setItem('hm-unlocked','1');$('#lockScreen').classList.add('hidden');startGreeting();startReminderChecker()}else{$('#unlockError').textContent='That PIN did not match.';if(state.settings.sound)chime('error')}};$('#unlockPin').addEventListener('keydown',e=>{if(e.key==='Enter')$('#unlockBtn').click()});

$('#addSchedule').onclick=()=>{const taskId=$('#schedTask').value;if(!taskId)return;state.schedule.push({id:uid('sched_'),taskId,mode:$('#schedMode').value,day:Number($('#schedDay').value),repeat:$('#schedRepeat').value,memberId:$('#schedMember').value||null,time:$('#schedTime').value||'18:00',startDate:new Date().toISOString()});save();renderAll();toast('Added to the HouseMade schedule');if(state.settings.sound)chime('pop')};
$('#addMember').onclick=()=>{const name=$('#memberName').value.trim();if(!name){toast('Add a name first');return}state.members.push({id:uid('member_'),name,channel:$('#memberChannel').value,contact:$('#memberContact').value.trim()});$('#memberName').value='';$('#memberContact').value='';save();renderAll();toast(`${name} added`);if(state.settings.sound)chime('pop')};
$('#newTask').onclick=()=>{const t={id:uid('task_'),name:'Custom task',icon:'sparkle',color:'#B59EE2',quick:[],deep:[]};state.library.push(t);save();renderTasks();editTask(t.id)};
$('#addPreset').onclick=()=>{const v=$('#newPreset').value.trim();if(!v)return;if(!state.presetItems.some(x=>x.toLowerCase()===v.toLowerCase()))state.presetItems.push(v);$('#newPreset').value='';save();renderPresetLibrary();toast('Added to master task library')};
$('#saveSettings').onclick=()=>{state.profile.firstName=$('#settingsName').value.trim()||state.profile.firstName;state.householdName=$('#settingsHouse').value.trim()||'Our House';state.settings.musicUrl=$('#musicUrl').value.trim();state.settings.defaultTimer=Math.max(1,Number($('#defaultTimer').value)||15);save();renderSettings();toast('Settings saved');startGreeting()};
$('#soundToggle').onclick=()=>{state.settings.sound=!state.settings.sound;save();renderSettings();if(state.settings.sound)chime('shimmer')};$('#themeToggle').onclick=()=>{state.settings.night=!state.settings.night;save();renderSettings()};$('#lockNow').onclick=()=>{if(!state.profile.pinHash){toast('Set a PIN during setup to use Lock now');return}sessionStorage.removeItem('hm-unlocked');showLock()};

function editTask(id){const t=getTask(id);if(!t)return;$('#editTaskId').value=id;$('#editTaskName').value=t.name;$('#editColor').value=t.color;$('#editHeading').textContent=t.name;renderIconPicker(t.icon);renderPresetGrid('quick',t);renderPresetGrid('deep',t);$('#editQuick').value='';$('#editDeep').value='';$('#editTaskModal').classList.remove('hidden')}
function renderIconPicker(active){const wrap=$('#iconPicker');wrap.innerHTML='';ICON_KEYS.forEach(k=>{const b=document.createElement('button');b.className='icon-choice'+(k===active?' active':'');b.dataset.icon=k;b.innerHTML=iconMarkup(k);b.onclick=()=>{$$('.icon-choice').forEach(x=>x.classList.remove('active'));b.classList.add('active')};wrap.appendChild(b)})}
function renderPresetGrid(mode,t){const wrap=$(`#${mode}Presets`);wrap.innerHTML='';state.presetItems.forEach(item=>{const b=document.createElement('button');b.className='preset-option'+(t[mode].includes(item)?' selected':'');b.dataset.item=item;b.innerHTML=`<span class="preset-check">${t[mode].includes(item)?'✓':''}</span><span></span>`;b.lastElementChild.textContent=item;b.onclick=()=>{b.classList.toggle('selected');b.querySelector('.preset-check').textContent=b.classList.contains('selected')?'✓':'';updatePresetCount(mode)};wrap.appendChild(b)});updatePresetCount(mode)}
function updatePresetCount(mode){$(`#${mode}Count`).textContent=`${$$(`#${mode}Presets .selected`).length} selected`}
$('#closeEdit').onclick=()=>$('#editTaskModal').classList.add('hidden');
$('#saveTaskEdit').onclick=()=>{const t=getTask($('#editTaskId').value);if(!t)return;t.name=$('#editTaskName').value.trim()||t.name;t.color=$('#editColor').value;t.icon=$('.icon-choice.active')?.dataset.icon||t.icon;['quick','deep'].forEach(mode=>{const selected=$$(`#${mode}Presets .selected`).map(b=>b.dataset.item);const customs=$(`#edit${mode[0].toUpperCase()+mode.slice(1)}`).value.split('\n').map(x=>x.trim()).filter(Boolean);t[mode]=[...new Set([...selected,...customs])]});save();$('#editTaskModal').classList.add('hidden');renderAll();toast('Task profile saved');if(state.settings.sound)chime('pop')};

function openTask(item,date){currentTask={...item,date:new Date(date)};currentMode=item.mode||'quick';timer.selected=state.settings.defaultTimer||15;resetTimer();const t=getTask(item.taskId);$('#taskTitle').textContent=t.name;$('#taskMaster').style.setProperty('--task',t.color);$('#taskMaster').innerHTML=iconMarkup(t.icon);$('#taskSheet').style.setProperty('--task',t.color);$$('.mode-tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===currentMode));renderTaskMode();newQuote();$('#taskModal').classList.remove('hidden')}
function renderTaskMode(){const t=getTask(currentTask.taskId),rec=completionFor(currentTask,currentTask.date,currentMode),items=t[currentMode];$('#taskModeLabel').textContent=currentMode==='deep'?'DEEP CLEAN':'QUICK CLEAN';$('#taskProgressText').textContent=`${rec.done.length} of ${items.length} complete`;const wrap=$('#subtasks');wrap.innerHTML='';items.forEach((name,i)=>{const done=rec.done.includes(name);const b=document.createElement('button');b.className='subtask'+(done?' done':'');b.style.setProperty('--task',t.color);b.innerHTML=`<span class="subtask-circle">${done?'✓':''}</span><span></span>`;b.lastElementChild.textContent=name;b.onclick=()=>toggleSubtask(name,b);wrap.appendChild(b)});$('#taskMaster').classList.toggle('gold',!!rec.all);$('#startTaskText').textContent=timer.running?'Pause timer':'Let’s get this house made'}
$$('.mode-tab').forEach(b=>b.onclick=()=>{currentMode=b.dataset.mode;$$('.mode-tab').forEach(x=>x.classList.toggle('active',x===b));renderTaskMode();newQuote();if(state.settings.sound)chime('soft')});
function toggleSubtask(name,button){const key=completionKey(currentTask,currentTask.date,currentMode),t=getTask(currentTask.taskId),rec=state.completions[key]||{done:[],all:false};const set=new Set(rec.done);const was=set.has(name);was?set.delete(name):set.add(name);rec.done=[...set];rec.all=t[currentMode].length>0&&t[currentMode].every(x=>set.has(x));state.completions[key]=rec;save();if(!was&&state.settings.sound)chime('pop');renderTaskMode();renderPlanner();renderUpNext();updateNotificationDot();if(rec.all&&!was)celebrateCompletion(t)}
function newQuote(){const q=QUOTES[Math.floor(Math.random()*QUOTES.length)];$('#quoteText').textContent=q;const dust=$('#quoteDust');dust.classList.remove('quote-dust');void dust.offsetWidth;dust.classList.add('quote-dust')}
$('#anotherQuote').onclick=newQuote;$('#closeTask').onclick=()=>{$('#taskModal').classList.add('hidden');stopTimer(false)};
function celebrateCompletion(task){const buttons=$$('#subtasks .subtask');buttons.forEach((b,i)=>setTimeout(()=>{b.classList.add('celebrate');setTimeout(()=>b.classList.remove('celebrate'),550);if(state.settings.sound&&i%2===0)chime('soft')},i*110));setTimeout(()=>{$('#taskMaster').classList.add('gold');if(state.settings.sound)chime('win');setTimeout(()=>showCompletion(task),500)},buttons.length*110+250)}
function showCompletion(task){$('#completionRoom').textContent=`${task.name} complete!`;$('#completionQuote').textContent=QUOTES[Math.floor(Math.random()*QUOTES.length)];createConfetti();$('#completionOverlay').classList.remove('hidden')}
function createConfetti(){const wrap=$('#confettiField');wrap.innerHTML='';const colors=['#B59EE2','#E0B44D','#F3A7B8','#86C9D8','#9FD6C1','#FFFFFF'];for(let i=0;i<70;i++){const p=document.createElement('i');p.style.left=`${Math.random()*100}%`;p.style.setProperty('--c',colors[Math.floor(Math.random()*colors.length)]);p.style.setProperty('--dur',`${2.4+Math.random()*2}s`);p.style.setProperty('--delay',`${Math.random()*.8}s`);p.style.setProperty('--drift',`${-100+Math.random()*200}px`);wrap.appendChild(p)}}
$('#completionClose').onclick=()=>{$('#completionOverlay').classList.add('hidden');$('#taskModal').classList.add('hidden');renderAll()};

$$('.timer-presets button').forEach(b=>b.onclick=()=>{timer.selected=Number(b.dataset.minutes);$$('.timer-presets button').forEach(x=>x.classList.toggle('active',x===b));resetTimer();if(state.settings.sound)chime('soft')});
function resetTimer(){stopTimer(false);timer.total=timer.selected*60;timer.remaining=timer.total;updateTimerDisplay()}
function updateTimerDisplay(){const m=Math.floor(timer.remaining/60),s=timer.remaining%60;$('#timerReadout').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;const p=timer.total?1-timer.remaining/timer.total:0;$('#timerRing').style.strokeDashoffset=314.16*p;$('#startTaskText').textContent=timer.running?'Pause timer':'Let’s get this house made'}
function startTimer(){if(timer.running){stopTimer(true);return}if(timer.remaining<=0)resetTimer();timer.running=true;if(state.settings.sound)chime('start');timer.id=setInterval(()=>{timer.remaining--;if(timer.remaining<=5&&timer.remaining>0&&state.settings.sound)chime('tick');if(timer.remaining<=0){timer.remaining=0;stopTimer(false);updateTimerDisplay();if(state.settings.sound)chime('win');toast('Time! Look what you got done ✦');showLocalNotification('HouseMade timer','Time! Your focus session is complete.');return}updateTimerDisplay()},1000);updateTimerDisplay()}
function stopTimer(keep=true){if(timer.id)clearInterval(timer.id);timer.id=null;timer.running=false;if(!keep&&timer.total===0){timer.total=timer.selected*60;timer.remaining=timer.total}updateTimerDisplay()}
$('#startTask').onclick=()=>{const starting=!timer.running;if(starting&&state.settings.musicUrl)window.open(state.settings.musicUrl,'_blank','noopener,noreferrer');startTimer()};$('#taskMusic').onclick=()=>{if(!state.settings.musicUrl){toast('Add a playlist link in Settings');return}window.open(state.settings.musicUrl,'_blank','noopener,noreferrer')};$('#taskReminder').onclick=()=>{const t=getTask(currentTask.taskId);showLocalNotification('HouseMade',`${t.name} is waiting for you.`);toast('Reminder notification sent')};

function openReminder(member){currentMember=member;$('#reminderMember').textContent=member.name;generateReminder();$('#reminderModal').classList.remove('hidden')}
function assignedTaskName(member){const item=state.schedule.find(s=>s.memberId===member.id);return getTask(item?.taskId)?.name||'HouseMade chore'}
function generateReminder(){const t=assignedTaskName(currentMember),fn=REMINDER_TEMPLATES[Math.floor(Math.random()*REMINDER_TEMPLATES.length)];$('#reminderText').value=fn(currentMember.name,t)}
$('#regenReminder').onclick=generateReminder;$('#closeReminder').onclick=()=>$('#reminderModal').classList.add('hidden');$('#copyReminder').onclick=async()=>{await navigator.clipboard.writeText($('#reminderText').value);toast('Reminder copied')};$('#sendReminder').onclick=()=>{const text=$('#reminderText').value,m=currentMember;if(m.channel==='sms'&&m.contact){location.href=`sms:${encodeURIComponent(m.contact)}?&body=${encodeURIComponent(text)}`;return}if(m.channel==='email'&&m.contact){location.href=`mailto:${encodeURIComponent(m.contact)}?subject=${encodeURIComponent('HouseMade chore reminder')}&body=${encodeURIComponent(text)}`;return}navigator.clipboard.writeText(text);toast(m.channel==='alexa'?'Alexa-ready prompt copied':'Reminder copied')};$('#setLocalReminder').onclick=async()=>{const minutes=Math.max(1,Number($('#reminderDelay').value)||10);await ensureNotifications();setTimeout(()=>showLocalNotification('HouseMade reminder',$('#reminderText').value),minutes*60000);toast(`Local reminder set for ${minutes} min`) };

async function ensureNotifications(){if(!('Notification'in window)){toast('Notifications are not supported on this device');return false}if(Notification.permission==='granted'){state.settings.notifications=true;save();return true}const p=await Notification.requestPermission();state.settings.notifications=p==='granted';save();renderSettings();return p==='granted'}
async function showLocalNotification(title,body){if(!(await ensureNotifications()))return;try{const reg=await navigator.serviceWorker?.ready;if(reg?.showNotification)await reg.showNotification(title,{body,icon:'./icon-192.png',badge:'./icon-192.png',tag:'housemade-reminder',renotify:true});else new Notification(title,{body,icon:'./icon-192.png'})}catch{try{new Notification(title,{body,icon:'./icon-192.png'})}catch{}}}
$('#enableNotifications').onclick=async()=>{if(await ensureNotifications()){toast('HouseMade notifications enabled');showLocalNotification('HouseMade','Notifications are ready ✦')}};$('#notificationBell').onclick=async()=>{if(await ensureNotifications())showLocalNotification('HouseMade','Your next chore is waiting when you’re ready.')};$('#testNotification').onclick=async()=>{if(await ensureNotifications())showLocalNotification('HouseMade','Notifications are ready. Tiny victory unlocked ✦')};
let reminderChecker=null;function startReminderChecker(){if(reminderChecker)return;checkScheduledReminders();reminderChecker=setInterval(checkScheduledReminders,30000)}
function checkScheduledReminders(){if(!state.settings.notifications||Notification.permission!=='granted')return;const now=new Date(),today=dateKey(now),minutes=now.getHours()*60+now.getMinutes();state.schedule.filter(s=>occursOn(s,now)).forEach(item=>{const [h,m]=(item.time||'18:00').split(':').map(Number),target=h*60+m,key=`${item.id}:${today}`;if(minutes>=target&&minutes<target+3&&!state.notificationHistory[key]&&!isComplete(item,now)){const t=getTask(item.taskId),member=state.members.find(x=>x.id===item.memberId);showLocalNotification(member?`HouseMade · ${member.name}`:'HouseMade',`${t.name} · ${item.mode==='deep'?'Deep Clean':'Quick Clean'} is on the schedule.`);state.notificationHistory[key]=Date.now();save()}})}

function chime(kind){try{const c=new(window.AudioContext||window.webkitAudioContext)();const now=c.currentTime;const seq=kind==='win'?[523,659,784,1046]:kind==='shimmer'?[784,988,1175,1568]:kind==='start'?[392,523,659]:kind==='error'?[260,210]:kind==='tick'?[740]:kind==='soft'?[620]:[660,880];seq.forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.type=kind==='win'||kind==='shimmer'?'sine':'triangle';o.frequency.setValueAtTime(f,now+i*.075);g.gain.setValueAtTime(.0001,now+i*.075);g.gain.exponentialRampToValueAtTime(kind==='tick'?.025:.05,now+i*.075+.012);g.gain.exponentialRampToValueAtTime(.0001,now+i*.075+.16);o.connect(g);g.connect(c.destination);o.start(now+i*.075);o.stop(now+i*.075+.18)})}catch{}}

$('#closeReminder').addEventListener('click',()=>{});document.addEventListener('keydown',e=>{if(e.key==='Escape'){$$('.modal:not(.hidden)').forEach(m=>m.classList.add('hidden'));$('#completionOverlay').classList.add('hidden')}});
window.addEventListener('online',()=>toast('Back online'));window.addEventListener('offline',()=>toast('Offline — HouseMade still works'));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
setupGate();
